updated gitignore
teamforus/forus-frontend-angular pull request #1047
Opened 2020-03-18 15:13 UTC by SjoerdHilhorst

2020-03-23 16:01 UTC, maxvisser requested changes
works; sample file should be moved to right directory and aswell be cleaned up a bit. Alot of unnessecary lines. As well as some variables are missing.

Could you also check why this test failed:
1) testing basic requester functionality: opens and closes start activation modal
  Message:
    Failed: No element found using locator: By(css selector, [ng-click="$ctrl.openAuthCodePopup()"])

as you suggested in chat, it could be that the test was still logged in.

2020-03-23 16:05 UTC, maxvisser commented on src/sources/forus-platform/pug/tpl/pages/sign-up.pug
> +                a(translate="sign_up.buttons.next" ng-click="$ctrl.next()" id='next-4').button.button-primary
I would use " instead of '

2020-03-23 16:50 UTC, maxvisser commented
single format for id; suggestion is Snake Case

2020-03-27 08:52 UTC, maxvisser commented
https://github.com/teamforus/forus-frontend/pull/1047/files/07399a24ab8f1e3b8713d8896ebfcf137b4a5255#diff-ff9128d90e5fb486bb30f64d2637b130 is not fixed yet

2020-03-27 08:54 UTC, maxvisser commented
As you use classes, ui-refs and or other existing html tags your test now can easily break by changing styles or texts. I would suggest to still change all by.css, by.className and others to by.id

2020-03-27 08:55 UTC, maxvisser commented on src/sources/forus-platform/pug/tpl/pages/products.pug
> +            a(ng-click="$ctrl.addProduct()" id="addProduct").link
Snakecase

2020-03-30 09:25 UTC, SjoerdHilhorst commented
https://www.protractortest.org/#/style-guide
> Prefer protractor-specific locators such as by.model and by.binding.

protractor zegt dat by.model wel een goede locator is, maar jouw keuze natuurlijk

2020-03-30 09:36 UTC, maxvisser commented
I would just add each last part of the ng-model as an id field
example:
```html
<input
ng-model="$ctrl.signUpForm.values.records.primary_email"
id="primary_email" />
```
if any of these variables will change $ctrl.signUpForm.values.records your test would fail. With using the ID's I can't really see how it could fail. (only if the field is removed or altered.)

2020-03-31 12:21 UTC, maxvisser requested changes
Couuld you still fix the comments I had left

2020-03-31 12:21 UTC, maxvisser commented on src/sources/forus-platform/pug/tpl/pages/landing/sign-up.pug
> +                    button(ng-click="$ctrl.next()" id='3' translate="sign_up.buttons.next").button.button-primary
Snakecase and '' -> to ""

2020-03-31 12:21 UTC, maxvisser commented on src/package-lock.json
> +<<<<<<< HEAD
@SjoerdHilhorst regenerate lock file

2020-03-31 12:21 UTC, maxvisser commented on src/sources/forus-platform/pug/tpl/pages/landing/sign-up.pug
> +                    button(ng-click="$ctrl.next()" id='3' translate="sign_up.buttons.next").button.button-primary
forgot this one?

2020-04-02 10:26 UTC, maxvisser commented
revert package-lock.json as there were merge conflicts pushed

@dev-rminds could you code review this?

2020-04-03 13:10 UTC, SjoerdHilhorst commented
for some weird reason some git conflicts did not show up in vscode, but i think it's all fixed. Updated the dashboard testcases for the new way of selection a fund. dashboard testcases are (lightly) dependent on LoremDbSeeder so you need to run that first and then run the tests

2020-06-04 08:55 UTC, GerbenBosschieter commented
@maxvisser What about this one. It's already open for a while. What is the hold up ?

2020-06-04 09:59 UTC, maxvisser commented
@dev-rminds will review it after finishing notification/digest. He need some time to get into this issue as the scope is pretty big

2020-06-04 10:05 UTC, jamalv commented
@maxvisser could you give rough estimations on both those things? I think since merging this is blocked by the check of valentin, that it's pretty important to review this. Since I agree with gerben that this has been open for quite a while now.

2020-06-04 10:15 UTC, maxvisser commented
I think this weekend there should be time. If the other tasks are finished.

2020-06-22 11:57 UTC, maxvisser commented
fine to merge!

Questions: I there a reason that:
local version is not checking the email
remote version is not checking the validator dashboard

_ added some env variables like email port etc.

- added a test task (which combines browserstack and protractor)

feedback:
- some functions, are 'one time use'-functions, not sure if this is a best practice. For now its fine

some test were failing 
- in a random order each run
![image](https://user-images.githubusercontent.com/10818702/85284326-4938be80-b48f-11ea-8061-ddad28ea22c8.png)

- we got a ssl routine, wrong version number error

Tips:
protractor can be used without gulp
@dev-rminds would create everything within the tests (instead of using a seeder)
later phase create cli client -> would help with directly testing the api
Later:
- add more scenario's

2020-06-22 12:03 UTC, maxvisser approved these changes

2020-06-22 12:03 UTC, merged

2020-06-22 15:49 UTC, SjoerdHilhorst commented
What exactly do you mean with local and remote?
and are these also questions or statements? 
> added some env variables like email port etc.

>added a test task (which combines browserstack and protractor

The mail listener was still something left over from when i tested complete flows. and currently not used for testing. I could remove it, but i can probably also make some useful testcases with it.

Could you clarify on not checking validator dashboard, when running it should just execute all test suites.

protractor is already able to run without gulp, run: `protractor test/e2e/protractor.conf.js`