Unassigned vouchers, add pdf export option
teamforus/forus-frontend-angular pull request #1048
Opened 2020-03-18 18:55 UTC by aghimpu

https://github.com/teamforus/forus/issues/1198

2020-03-23 01:48 UTC, dev-rminds commented
@maxvisser could you please check export format icons (.png/.pdf) and request new icons from the designers if “.mdi” icons are not fine.

2020-03-23 14:46 UTC, maxvisser commented
![image](https://user-images.githubusercontent.com/10818702/77328814-5d98de00-6d1d-11ea-93e4-72bf5c243758.png)
@danrminds could find some better fitting icons with @sashooa

2020-03-23 14:46 UTC, maxvisser requested changes
- [x] change png/pdf icons
- [x] add dutch locatization
Title: Selecteer export type
Export as png: Exporteer als afbeelding
Export as pdf: Exporteer als één pdf-bestand
Confirm: Bevestig

2020-03-25 09:51 UTC, maxvisser approved these changes

2020-03-25 09:51 UTC, merged