Release/v0.10.0
teamforus/forus-frontend-angular pull request #1075
Opened 2020-04-06 13:43 UTC by maxvisser

changelog:
- New provider signupflow
- settings page: email settings
- Unassigned vouchers, add pdf export option
- Modal fund request clarification, fix icon overflow
- Webshop, update some page titles
- Modal pdf preview, update translation
- Make CSV upload on voucher generator qdt-env configurable via flags
- Dashboards, add organization switcher
- Allow signups usage on tablets
- Berkelland: Provider landing page, fix header image issue on IE
- Fund selector adjustments
- Navbar, replace logo with higher quality
- refactoring, feedback, removed alerts and redirects on some pages

2020-04-19 20:04 UTC, GerbenBosschieter approved these changes
- Webshop frontend bug with IIE. Only displays footer. Should be fixed before release

2020-04-19 20:17 UTC, GerbenBosschieter requested changes
Accidentally approved last review.
- Webshops do not work on IE.
- Website doesn't work on IE (this was already the case, but would be nice to also fix this for the release)
- Sign up v2 doesn't work either on Ie

2020-04-20 08:06 UTC, maxvisser commented
when SESSIONS_GEO_IP_ENABLED is set to true Internet explorer will stop working. (on backend)

2020-04-20 10:57 UTC, maxvisser commented
Still should be changed: hide email settings with a qdt-env flag from frontend

2020-04-21 12:54 UTC, GerbenBosschieter requested changes
Can't acces pages on IE:
- Provider dashboard
- Signup flows v1
- Also mentioning https://test-inkomensondersteuning.nijmegen.nl/provider/#!/ . Not sure but this but I think this is a separate pug file.

2020-04-21 13:11 UTC, maxvisser commented on src/sources/forus-platform/pug/layout/includes/scripts.pug
> +//- google maps
should be loaded after app.js and bundle.js

2020-04-21 16:38 UTC, GerbenBosschieter approved these changes

2020-04-22 05:25 UTC, merged