adjusted logo size dashboard
teamforus/forus-frontend-angular pull request #1169
Opened 2020-06-01 09:36 UTC by SjoerdHilhorst

2020-06-04 08:29 UTC, GerbenBosschieter commented on src/sources/forus-platform/scss/_common/landing.scss
> +                margin: 15px 0px auto auto;
Remove margin. This results into weird result on mobile.

2020-06-04 08:30 UTC, GerbenBosschieter commented on src/sources/forus-platform/scss/_common/landing.scss
> +                height: 20px;
To small. If. choose 30 it's okay.

2020-06-04 08:32 UTC, GerbenBosschieter commented on src/sources/forus-platform/scss/_common/landing.scss
> +                padding: 20px 25px 20px 0;
In combination with my earlier feedback, adding this much padding: 30px 30px should do the job.

2020-06-04 08:36 UTC, GerbenBosschieter requested changes
@SjoerdHilhorst I'have left some comments.
I can see that you made some changes to the common file.
Changing css in the common file can result into unintentionally changes to other implementations.

I tried to check if other implementations where influenced by the changes you made. Didn't look like it had any issues. But couldn't check everything

2020-07-22 07:15 UTC, maxvisser commented
@GerbenBosschieter Will you review this again?

2020-07-24 14:33 UTC, merged