Add 404 page
teamforus/forus-frontend-angular pull request #1267
Opened 2020-08-04 20:16 UTC by dev-rminds

2020-08-05 09:16 UTC, maxvisser commented on src/sources/forus-webshop/js/angular-1/i18n/nl/pages/error-page.js
> +        title: 'Page not found',
Pagina niet gevonden

2020-08-12 13:40 UTC, maxvisser commented
![image](https://user-images.githubusercontent.com/10818702/90021836-0edee700-dcb2-11ea-9176-126c8d495e48.png)
Seems to be english? Not sure why

2020-08-12 13:44 UTC, maxvisser commented
Back to home button does not seem to work

2020-08-12 13:44 UTC, maxvisser requested changes
- Page should be dutch
- Back to home button should return user to home.

2020-08-12 13:45 UTC, maxvisser commented
Not sure if this will work on staging. Needs testing there before merging.

2020-08-17 20:28 UTC, GerbenBosschieter approved these changes

2020-08-26 13:50 UTC, merged