Fix disregard undo button
teamforus/forus-frontend-angular pull request #2352
Opened 2022-11-09 14:09 UTC by ateamcms

2022-11-14 12:31 UTC, lexlog requested changes
checked on dev. env.
main functionality "reopen" button works, but it still possible for the requester to apply for a fund. 
imho, if we disable fund application, we also need to create a new status for application in the webshop (postpone), otherwise having status "sign up" with blocked button is not very clear behaviour

assigning issue on Gerben to clarify later

2022-11-29 10:01 UTC, GerbenBosschieter commented
Reviewed it. Fits all the requirements.

2022-11-29 10:04 UTC, GerbenBosschieter approved these changes

2022-11-29 10:06 UTC, lexlog approved these changes

2022-11-29 10:15 UTC, merged