Updated Information About Us Page
teamforus/forus-frontend-angular pull request #2551
Opened 2023-03-07 16:28 UTC by Dominique2002

Here is an update of the information given on the current Forus about us page.

**Updated information includes:**

- Removal of the word "Stichting" (Foundation)
- Information given about Forus
- The team description
- Team members

2023-03-08 09:12 UTC, lexlog commented
for info, can't approve PR due to language barrier to check, but i changed base from master to develop - by our gitflow, PR-s should be created to develop branch

2023-03-16 15:57 UTC, RobinMeles approved these changes

2023-03-16 16:24 UTC, pathwaynavigator requested changes
Please change text and goededoelenorganisaties.

2023-03-16 16:29 UTC, pathwaynavigator approved these changes
Very noice.

2023-03-16 16:31 UTC, lexlog approved these changes

2023-03-16 17:04 UTC, merged