add input refocus on reservation birth date select, update validation…
teamforus/forus-frontend-angular pull request #2853
Opened 2023-07-27 13:56 UTC by aghimpu

… error message

## Changes description

## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## Developer suggestions
Checkmark if PR:
- [ ] *Needs Translations*
- [ ] *Could affect implementations custom css*
- [ ] *Need mobile design help/work*
- [ ] *Design include inconsistent*

## QA checklist
- [ ] Tag @ sashoa if design review needed
- [ ] *No regress in implementations custom css* - changes are not breaking other implementations designes
- [ ] Feature is tested in different screen sizes - desktop, mobile
- [ ] WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- [ ] Translations are done

2023-08-14 09:25 UTC, lexlog requested changes
tested on dev, scenarios that not succeed
- [ ] setting the day after setting year (can't set focus on days)
- [ ] closing calendar without setting the date

+ additional - if focus on last day of month, top fields of modal will be hidden, but modal won't become scrollable

all scenarios in one video
https://github.com/teamforus/forus-frontend/assets/8695780/d935a64e-61ad-498b-862e-61aa5961c8d0

@aghimpu could you please take a look?

2023-08-14 11:14 UTC, lexlog commented
update - was checking PR with reservation modal redesign and seems its fixed there, i will retest this after those PR

2023-08-14 21:41 UTC, aghimpu commented
2-3 hours needed for research to implement the feedback (the library itself doesn't provide any way to implement those changes either)

2023-08-16 13:27 UTC, lexlog approved these changes

2023-08-16 13:32 UTC, lexlog approved these changes

2023-08-16 13:32 UTC, merged