Feature sign up flow url filter
teamforus/forus-frontend-angular pull request #783
Opened 2019-11-16 21:54 UTC by aghimpu

https://github.com/teamforus/forus/issues/1097

2019-11-18 13:53 UTC, maxvisser commented
labels can be added to i18n

2019-11-21 10:38 UTC, maxvisser requested changes

2019-11-21 10:38 UTC, maxvisser commented on src/sources/forus-platform/pug/tpl/pages/sign-up.pug
> +                            .form-label Organizations
translate to: Organisaties

2019-11-21 10:38 UTC, maxvisser commented on src/sources/forus-platform/js/angular-1/components/SignUpComponent.js
> +            $ctrl.fundLabels.unshift({ key: 'null', name: 'All Labels' });
Translate: Alle labels

2019-11-21 10:38 UTC, maxvisser commented on src/sources/forus-platform/js/angular-1/components/SignUpComponent.js
> +            $ctrl.fundOrganizations.unshift({ id_str: 'null', name: 'All Organizations' });
Translate: Alle organisaties

2019-11-21 10:38 UTC, maxvisser commented on src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
> +            all_organizations: 'All organizations',
Alle organisaties

2019-11-21 10:38 UTC, maxvisser commented on src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
> +            all_labels: 'All labels'
Alle labels

2019-11-24 14:06 UTC, maxvisser approved these changes

2019-11-24 14:25 UTC, maxvisser commented
@dev-rminds backend is also ready for review?

2019-11-25 10:11 UTC, dev-rminds commented
> @dev-rminds backend is also ready for review?

Ready for testing

2019-11-26 12:58 UTC, maxvisser commented
fund_id does not work anymore.

2019-11-26 13:15 UTC, merged