Webshop, voucher page small adjustments on the voucher card
teamforus/forus-frontend-angular pull request #892
Opened 2019-12-24 19:00 UTC by aghimpu

https://github.com/teamforus/forus/issues/1283

2019-12-26 08:23 UTC, maxvisser requested changes
![image](https://user-images.githubusercontent.com/10818702/71466810-07b9a600-27c1-11ea-9648-4d90271e532a.png)

1. margin-top 10px should be margin-bottom 10px 
2. there is a space missing between this data E-mailadres:optisport@forus.io should be E-mailadres: optisport@forus.io (space is also missing on phonenumber

2019-12-27 11:22 UTC, aghimpu commented
>> margin-top 10px should be margin-bottom 10px
These are some old styles, the margins weren't really modified by me earlier, but I'll commit the requested change.

>> there is a space missing between this data E-mailadres:optisport@forus.io should be E-mailadres: optisport@forus.io (space is also missing on phonenumber
What implementation is that one? I don't see it on webshop general

2019-12-27 11:23 UTC, maxvisser commented
I think I took screenshot on Nijmegen not sure.

2019-12-28 09:36 UTC, maxvisser approved these changes

2019-12-28 09:36 UTC, merged